steps:
- name: 'gcr.io/cloud-builders/npm'
  args: [install]
- name: 'gcr.io/cloud-builders/npm'
  args: [install]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','_NODE_ENV/my-image .']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/mcc-ai-poc/my-image']